services:
  # Serviço para o Laravel (PHP + Apache)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www
    networks:
      - app-network
    depends_on:
      - db

  react:
    image: node:18
    container_name: react-container
    working_dir: /usr/src/app
    command: sh -c "npm start"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/my-app:/usr/src/app
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: laravel_web
    command: "php artisan serve --host 0.0.0.0"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - app-network    

  # Banco de Dados MySQL
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: ecommerce_password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  # PHPMyAdmin para gerenciamento do banco de dados
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  dbdata:


networks:
  app-network:
    driver: bridge
