version: '3'
services:
  app:
    build: 
      args: 
        user: derio
        uid: 1000
      context: ./
      dockerfile: Dockerfile  
    image: ecommerce-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-eti

  nginx:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - 8000:80
      - 443:443
    volumes:
      - ./:/var/www/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/  
    networks:
      - laravel-eti

  db:
    image: mysql:5.7.22
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USERNAME: ${DB_USERNAME}
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql 
      - ./mysql/my.cnf:/etc/mysql/my.cnf 
    networks:
      - laravel-eti  

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8082:80"
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    networks:
      - laravel-eti

#Docker Networks
networks:
  laravel-eti:
    driver: bridge